name: marinuata_app
description: App de monitoramento pesqueiro offline-first.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Banco Local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8  # <--- ADICIONAR/VERIFICAR ESTE
  google_sign_in: ^6.2.1

  # Estado
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Utilitários
  uuid: ^4.2.1
  intl: ^0.19.0
  gap: ^3.0.0
  geolocator: ^10.1.0       # <--- ADICIONAR/VERIFICAR ESTE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # --- Geradores de Código ---
  build_runner: ^2.4.8
  isar_generator: ^3.1.0
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  # --- Imagens / Logos ---
  # Crie uma pasta chamada 'assets' na raiz do projeto e coloque suas imagens lá.
  assets:
    - assets/